# Generated by Django 5.2.6 on 2025-09-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='organization',
        ),
    ]
