# Generated by Django 5.2.6 on 2025-09-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_remove_event_attendees_attendee_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events', to='eventapp.attendee'),
        ),
    ]
