# Generated by Django 5.2.6 on 2025-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_remove_attendee_event_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
