# Generated by Django 5.2.6 on 2025-09-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_event_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event',
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
