# Generated by Django 5.2.6 on 2025-09-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_remove_event_event_attendee_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='event',
            field=models.CharField(blank=True, null=True),
        ),
    ]
