# Generated by Django 5.2.6 on 2025-09-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_alter_attendee_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Active', 'Active'), ('Past', 'Past')], default='Upcoming'),
        ),
    ]
