# Generated by Django 5.2.6 on 2025-09-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0010_alter_attendee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
