# Generated by Django 5.2.6 on 2025-09-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0011_attendee_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='attendee',
            field=models.BooleanField(default=False),
        ),
    ]
