# Generated by Django 5.2.6 on 2025-09-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0012_attendee_attendee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='attendee',
            new_name='attended',
        ),
    ]
